services:
  yolo-api:
    image: ${IMAGE:-ghcr.io/pedropalacioo/yolo-edge-api/yolo-api:latest}
    build:
      context: .
      dockerfile: Dockerfile.api

    container_name: yolo-api

    ports:
      - "8000:8000"

    privileged: true

    volumes:
      - ./models:/app/models:ro
      - ./output:/app/output
      - ./images:/app/images:ro
      - /dev:/dev
      - /run/udev:/run/udev:ro

    environment:
      - MODEL_NAME=yolov8n.pt

    networks:
      - yolo-net

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3


  yolo-client:
    build:
      context: .
      dockerfile: Dockerfile.client

    container_name: yolo-client

    volumes:
      - ./images:/client/images:ro
      - ./output:/client/output

    environment:
      - API_URL=http://yolo-api:8000

    networks:
      - yolo-net

    depends_on:
      yolo-api:
        condition: service_healthy

  yolo-stream:
    build:
      context: .
      dockerfile: Dockerfile.stream

    container_name: yolo-stream

    ports:
      - "5000:5000"

    privileged: true

    volumes:
      - ./models:/app/models:ro
      - /dev:/dev
      - /run/udev:/run/udev:ro

    environment:
      MODEL_PATH: models/yolov8n.pt
      CAMERA_INDEX: "0"
      CAMERA_WIDTH: "1280"
      CAMERA_HEIGHT: "720"
      CAMERA_FPS: "30"
      INFERENCE_SIZE: "416"
      INFER_EVERY: "2"
      JPEG_QUALITY: "80"
      YOLO_CONFIG_DIR: /tmp/Ultralytics

    networks:
      - yolo-net

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s


networks:
  yolo-net:
    driver: bridge
