FROM python:3.11-slim

WORKDIR /client

# Copia e instala as dependências do cliente
COPY client/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

# Copia o código do cliente
COPY client/client.py ./client.py

CMD ["python", "client.py"]
